apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    io.kompose.service: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: telegraf
    spec:
      containers:
      - name: telegraf
        image: image-telegraf
        imagePullPolicy: Never
        ports:
        - containerPort: 4999
        volumeMounts:
        - name: config
          mountPath: "/etc/telegraf"
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        env:
          - name: USER
            value: telegraf
          - name: INFLUX_URL
            value: "http://192.168.99.100:8086"
          - name: INFLUX_SKIP_DATABASE_CREATION
            value: "false"
          - name: INFLUX_PASSWORD
            value: "services"
          - name: MINI_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
      volumes:
      - name: config
        configMap:
          name: telegraf-config
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
