apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: image-ftps
        imagePullPolicy: Never
        name: ftps
        env:
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ftps
              key: username
        - name: FTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps
              key: password
        - name: MINI_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 21
          hostPort: 21
        - containerPort: 21000
          hostPort: 21000
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
