apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    io.kompose.service: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        imagePullPolicy: Never
        image: image-phpmyadmin
        ports:
        - containerPort: 80
          name: http
