apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    io.kompose.service: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: grafana
    spec:
      containers:
      - name: grafana
        image: image-grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

