secretGenerator:
- name: ssh
  literals:
  - username=ak
  - password=123
- name: mysql
  literals:
  - username=root
  - password=1234
- name: ftps
  literals:
  - username=akerloc-
  - password=123

configMapGenerator:
- name: telegraf-config
  files:
  - telegraf.conf=config/telegraf.conf

resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - ingress.yaml
  - telegraf.yaml
  - influxdb.yaml
  - grafana.yaml
  - ftps.yaml
  - mysql-pv-claim.yaml
  - mysql-pv-volume.yaml
  - wp-pv-claim.yaml
  - wp-pv-volume.yaml
  - deployment-mysql.yaml
  - deployment-wordpress.yaml
  - deployment-phpmyadmin.yaml
  - service-mysql.yaml
  - service-wordpress.yaml
  - service-phpmyadmin.yaml
