secretGenerator:
- name: ssh
  literals:
  - username=ak
  - password=123
- name: mysql
  literals:
  - username=root
  - password=1234
- name: ftps
  literals:
  - username=akerloc-
  - password=123

configMapGenerator:
- name: telegraf-config
  files:
  - telegraf.conf=config/telegraf.conf

resources:
  - deployement-ftps.yaml
  - deployment-grafana.yaml
  - deployment-influxdb.yaml
  - deployment-mysql.yaml
  - deployment-nginx.yaml
  - deployment-phpmyadmin.yaml
  - deployment-telegraf.yaml
  - deployment-wordpress.yaml
  - pv-claim-ftps.yaml
  - pv-claim-influxdb.yaml
  - pv-claim-mysql.yaml
  - pv-claim-wordpress.yaml
  - pv-volume-influxdb.yaml
  - pv-volume-mysql.yaml
  - pv-volume-wordpress.yaml
  - ingress.yaml
  - service-ftps.yaml
  - service-grafana.yaml
  - service-influxdb.yaml
  - service-mysql.yaml
  - service-nginx.yaml
  - service-phpmyadmin.yaml
  - service-telegraf.yaml
  - service-wordpress.yaml
