secretGenerator:
- name: ssh
  literals:
  - username=akerloc-
  - password=1234
- name: mysql
  literals:
  - username=root
  - password=1234
- name: ftps
  literals:
  - username=akerloc-
  - password=1234

resources:
  - nginx.yaml
  - ingress.yaml