secretGenerator:
- name: ssh
  literals:
  - username=ak
  - password=123
- name: mysql
  literals:
  - username=root
  - password=1234
- name: ftps
  literals:
  - username=akerloc-
  - password=1234

resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - ingress.yaml