apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    io.kompose.service: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    io.kompose.service: nginx
spec:
  type: NodePort
  selector:
    io.kompose.service: nginx
  ports:
    - name: ssh
      port: 4000
      nodePort: 4000
    - name: https
      nodePort: 443
      port: 443
