apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    io.kompose.service: telegraf
spec:
  type: NodePort
  ports:
  - port: 4999
    nodePort: 4999
    protocol: TCP
    name: http
  selector:
    io.kompose.service: telegraf
