apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    io.kompose.service: influxdb
spec:
  ports:
  - port: 8086
    nodePort: 8086
    protocol: TCP
    name: influxdb
  selector:
    io.kompose.service: influxdb
  type: NodePort
